# Generated by Django 2.0 on 2020-04-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=30, unique=True)),
                ('PASSWORD', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DISEASE_NAME', models.CharField(max_length=30)),
                ('SYMPTOMS', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DISEASE_NAME', models.CharField(max_length=30)),
                ('SYMPTOMS', models.CharField(max_length=30)),
                ('MEDICINE_NAME', models.CharField(max_length=30)),
                ('MEDICINE_DESCRIPTION', models.CharField(max_length=30)),
            ],
        ),
    ]
